### ISSUE TITLE
Build: Webpack + Gulp

### ISSUE THREAD

**Issue by carolinaferreira** [gabrielsclimaco/GCS#1]
### Tasks: 
* [ ] Create webpack.config.js
* [ ] Create gulpfile.js
* [ ] Integrate Webpack and gulp

**Comment by carolinaferreira** [comment]
http://webpack.github.io/docs/usage-with-gulp.html

**Comment by carolinaferreira** [comment]
https://webpack.js.org/guides/integrations/#gulp

**Comment by carolinaferreira** [comment]
https://stackoverflow.com/questions/36897877/gulp-error-the-following-tasks-did-not-complete-did-you-forget-to-signal-async

**Comment by carolinaferreira** [comment]
https://stackoverflow.com/questions/42375468/uglify-syntaxerror-unexpected-token-punc
